Feature/homepage
AlexeyGrishechkin/movio pull request #2
Opened 2021-09-09 14:47 UTC by AlexeyGrishechkin

2021-09-11 09:34 UTC, alexanderchernetsky requested changes

2021-09-11 09:34 UTC, alexanderchernetsky commented on .gitignore
> +.DS_Store
You should create .env.example file and add to it names of env variables without values.

2021-09-11 09:34 UTC, alexanderchernetsky commented on package.json
> +    "babel-plugin-import": "^1.13.3",
In my view it's must have for every project to have Eslint. Also it would be additional "+" for your next career growth day.

2021-09-11 09:34 UTC, alexanderchernetsky commented on src/components/loader.js
> +    border-color: black transparent black transparent;
Property border-color overwrites property border. Could you please write it in one line?

2021-09-11 09:34 UTC, alexanderchernetsky commented on src/components/pagination.js
> +  const switchPage = (e, value) => {
What is the `e` argument? Please give all variables meaningful names.

2021-09-11 09:34 UTC, alexanderchernetsky commented on src/components/raitingFilm.js
> +  }
Seems like code in lines  6-11 is not used and can be removed.

2021-09-11 09:34 UTC, alexanderchernetsky commented on src/containers/homepage.jsx
> +  const renderMovie = () => {
It might be just my preference, but I think the rule of a thumb is: "The render() method and stateless components are the only places where JSX should be. If the rendering logic grows too big, split it into more components."

2021-09-11 09:34 UTC, alexanderchernetsky commented on src/styled/index.js
> +  padding: 1rem 3rem;
You should be using only 1 type of css units. px/rem or whatever else, but only 1.

2021-09-11 09:34 UTC, alexanderchernetsky commented on src/utils/axios.js
> +import axios from "axios";
I think axios is a part of your services. So logically it should be inside services dir.

2021-09-11 09:34 UTC, alexanderchernetsky commented on src/utils/axios.js
> +    // page: 1,
Please remove commented code.

2021-09-11 09:34 UTC, alexanderchernetsky commented on src/utils/constants.js
> +export const API_KEY = "585df56762c766c69dbc56c242d26a63";
Such things like URLs, passwords should NEVER be in your repository. It should be in .env file.

2021-09-11 09:34 UTC, alexanderchernetsky commented on src/utils/helpers/checkData.js
> +  if (data === 0 || data === null) {
Can we simplify it to !data ?

2021-09-11 09:34 UTC, alexanderchernetsky commented on src/utils/helpers/colorRating.js
> +export const colorRating = (rating) => {
It's a bad name for this function. It leads programmers to misapprehension. It should be named: "describeRating" or sth like this.

2021-09-11 09:34 UTC, alexanderchernetsky commented on src/utils/helpers/colorRating.js
> +    return "normal";
Is it logically correct that film with no rating or with 0 rating will be described as normal? Maybe you should add additional name like unknown or sth?

2021-09-11 09:34 UTC, alexanderchernetsky commented on src/containers/movieDescription.jsx
> +                `min. / ${minuteToHours(movie.runtime)}`
Do we need to show this `min. / ${minuteToHours(movie.runtime)}` if we don't have movie.runtime?

2021-09-11 09:34 UTC, alexanderchernetsky commented on src/components/pagination.js
> +import React from "react";
I noticed bug: 1) click page 2. 
2) refresh browser. 
Expected res: you're still on page 2.
Actual res: you're on page 1, but in URL we have page 2.

2021-09-11 09:34 UTC, alexanderchernetsky commented on src/containers/movieDescription.jsx
> +            <GoBackBtn onClick={goBack}>Back to menu</GoBackBtn>
All clickable elements should have cursor:pointer.

2021-09-11 09:34 UTC, alexanderchernetsky commented on src/components/loader.js
> +import React from "react";
That's how the page looks during the loading: https://ibb.co/JjdCtXR Please correct gray background to fill the rest of the page OR remove it while loading.

2021-09-11 09:34 UTC, alexanderchernetsky commented on package.json
> +    "babel-plugin-import": "^1.13.3",
I would also recommend you to add husky and set up a pre-commit hook to check linting and prettify code.

2021-10-18 08:11 UTC, AlexeyGrishechkin commented on .gitignore
> +.DS_Store
created

2021-10-18 08:11 UTC, AlexeyGrishechkin commented on package.json
> +    "babel-plugin-import": "^1.13.3",
added

2021-10-18 08:12 UTC, AlexeyGrishechkin commented on src/components/loader.js
> +    border-color: black transparent black transparent;
fixed

2021-10-18 08:12 UTC, AlexeyGrishechkin commented on src/components/pagination.js
> +  const switchPage = (e, value) => {
renamed

2021-10-18 08:13 UTC, AlexeyGrishechkin commented on src/components/raitingFilm.js
> +  }
fixed

2021-10-18 08:13 UTC, AlexeyGrishechkin commented on src/utils/helpers/colorRating.js
> +    return "normal";
fixed

2021-10-18 08:14 UTC, AlexeyGrishechkin commented on src/containers/movieDescription.jsx
> +                `min. / ${minuteToHours(movie.runtime)}`
if we don`t have movie.runtime, we show "-"

2021-10-18 08:14 UTC, AlexeyGrishechkin commented on src/components/pagination.js
> +import React from "react";
fixed

2021-10-18 08:14 UTC, AlexeyGrishechkin commented on src/containers/movieDescription.jsx
> +            <GoBackBtn onClick={goBack}>Back to menu</GoBackBtn>
fixed

2021-10-18 08:14 UTC, AlexeyGrishechkin commented on src/components/loader.js
> +import React from "react";
removed

2021-10-21 11:50 UTC, alexanderchernetsky requested changes

2021-10-21 11:50 UTC, alexanderchernetsky commented on .eslintrc
> +  "extends": ["airbnb", "react-app", "prettier"],
There is no point in adding Eslint if all the rules are disabled. Please consider adding the following rules: 
"semi": [2, "always"],
"prefer-const": "error",
"no-console": "warn",
"import/no-unresolved": "error",
'object-shorthand': "error".
You can extend the list if you want. https://eslint.org/docs/rules/

2021-10-21 11:50 UTC, alexanderchernetsky commented on package.json
> +      "pre-commit": "lint-staged"
You should add "lint" in pre-commit check.

2021-10-21 11:50 UTC, alexanderchernetsky commented on package.json
> +      "./node_modules/.bin/eslint --fix",
lint-staged should call prettier. E.g.: 
```
"lint-staged": {
    "*.(js|ts|tsx)": [
      "prettier --write"
    ]
  },
```

2021-10-21 11:50 UTC, alexanderchernetsky commented on src/components/raitingFilm.js
> +  let hasRating = "";
It's a bad name for the string. I've already sent you a guide. Please use it.

2021-10-21 11:50 UTC, alexanderchernetsky commented on src/components/renderGenres.js
> +  const genreList = MovieStore.genres
I'd move this into a separate helper function. It should be sth like this: 
`const genreList = createGenreList(MovieStore.genres);`
We'll also add unit tests for this function in future.

2021-10-21 11:50 UTC, alexanderchernetsky commented on src/containers/homepage.jsx
> +            <RenderGenres
You should open your dev tools network tab from time to time to check if everything works as expected. In your case you're sending a lot of duplicate requests to get the genres list ("/genre/movie/list").  You should send only 1 request instead.

2021-10-21 11:50 UTC, alexanderchernetsky commented on src/components/pagination.js
> +      <Pagination
I've noticed a bug. To reproduce it:
1. open your app (1st page);
2. select page 2 via pagination;
3. click the browser back btn;
Expected result: pagination shows page 1 as active.
Current result: pagination shows page 2 as  active.

2021-10-22 09:03 UTC, alexanderchernetsky commented on package.json
> +      "pre-commit": "lint-staged"
I said: "You should add "lint" in pre-commit check." I didn't say that you should remove lint-staged :)

2021-10-22 09:07 UTC, alexanderchernetsky commented on package.json
> +      "pre-commit": "lint-staged"
Also you need to add a .prettierrc file with prettier configuration. It's not gonna work without it.

2021-10-22 09:15 UTC, alexanderchernetsky requested changes

2021-10-22 09:15 UTC, alexanderchernetsky commented on src/components/raitingFilm.jsx
> +    return false;
If you don't wanna return a component when `rating === 0`, you should return `null`.

2021-10-26 16:27 UTC, AlexeyGrishechkin commented on src/components/raitingFilm.js
> +  let hasRating = "";
fixed

2021-10-27 13:12 UTC, AlexeyGrishechkin commented on src/components/raitingFilm.jsx
> +    return false;
fixed

2021-10-27 13:12 UTC, AlexeyGrishechkin commented on package.json
> +      "pre-commit": "lint-staged"
fixed

2021-10-29 11:00 UTC, alexanderchernetsky commented
Pre-commit hook isn't working for me. Please investigate the issue.

2021-11-18 13:45 UTC, AlexeyGrishechkin commented
> Pre-commit hook isn't working for me. Please investigate the issue.

fixed

2021-11-20 08:16 UTC, alexanderchernetsky commented
Hi! Your pre-commit hook was not working for me. To make it work for everyone you need to add a "prepare": "husky install" script to your package.json file. Everyone who installs your project for the 1-st time will need to run "npm run prepare" to enable hooks. Also you need to add this info to the readme file.

2021-11-22 16:54 UTC, AlexeyGrishechkin commented
fixed

сб, 20 нояб. 2021 г. в 11:16, Alexander Chernetsky ***@***.***
>:

> Hi! Your pre-commit hook was not working for me. To make it work for
> everyone you need to add a "prepare": "husky install" script to your
> package.json file. Everyone who installs your project for the 1-st time
> will need to run "npm run prepare" to enable hooks. Also you need to add
> this info to the readme file.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/AlexeyGrishechkin/movio/pull/2#issuecomment-974614390>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AQUGF6RUHNDIUKKFTQDL7YDUM5KNPANCNFSM5DXKB5WA>
> .
>

2021-11-22 16:54 UTC, AlexeyGrishechkin commented
> Hi! Your pre-commit hook was not working for me. To make it work for everyone you need to add a "prepare": "husky install" script to your package.json file. Everyone who installs your project for the 1-st time will need to run "npm run prepare" to enable hooks. Also you need to add this info to the readme file.

fixed

2022-02-02 08:27 UTC, merged