add unit testing on project
AlexeyGrishechkin/movio pull request #3
Opened 2022-02-03 18:38 UTC by AlexeyGrishechkin

fix bug with showing total page
improve helpers function

2022-02-04 08:24 UTC, alexanderchernetsky requested changes

2022-02-04 08:24 UTC, alexanderchernetsky commented on src/utils/helpers/createGenreList.js
> +  const findGenresInGenresList = genreList.filter(
incorrect naming. It's not a function to be started from the verb "find". Example of correct name - genresFromGenresList

2022-02-04 08:24 UTC, alexanderchernetsky commented on src/utils/helpers/describeRating.js
> +  const convertRatingToNumber = Number(rating);
Incorrect naming. Can be ratingConvertedToNumber . As it's a number it should start from a noun.

2022-02-04 08:24 UTC, alexanderchernetsky commented on src/utils/helpers/describeRating.js
> +    convertRatingToNumber === 0 ||
convertRatingToNumber === 0 || !convertRatingToNumber - can be simplified to just !convertRatingToNumber

2022-02-04 08:24 UTC, alexanderchernetsky commented on src/utils/helpers/expandList.js
> +export const expandList = (list = []) => {
Bad name for the function. In fact it's building a string from the array. Expanding/collapsing is a different functionality. Please think of a better name.

2022-02-04 08:24 UTC, alexanderchernetsky commented on src/utils/helpers/expandList.js
> +  if (list.length === 0 || filterList.length === 0) {
No need to check list.length. filterList.length is what we are interested in.

2022-02-04 08:24 UTC, alexanderchernetsky commented on src/utils/helpers/tests/checkData.spec.js
> +describe("checkData gets two parameters and returns these joined parameters as string", () => {
In describe you should leave only function name. Please correct this in all tests

2022-02-04 08:24 UTC, alexanderchernetsky commented on src/utils/helpers/tests/checkData.spec.js
> +  test("get only one parameter and return string", () => {
I don't like the wording. It's much clearer to say: "given only 1 parameter - returns string containing this parameter"

2022-02-04 08:24 UTC, alexanderchernetsky commented on src/utils/helpers/tests/createGenreList.spec.js
> +const genreList = [
As it's a mock data it's name should start from "mock" by convention. E.g. mockGenreList.

2022-02-04 08:24 UTC, alexanderchernetsky commented on src/utils/helpers/tests/createGenreList.spec.js
> +describe("createGenreList get genreList array of objects with id and name and filmGenre array of number (genres id) and returns names of genre as string", () => {
Only "createGenreList" should be in the upper describe. Please correct the same mistake in all places.

2022-02-04 08:24 UTC, alexanderchernetsky commented on src/utils/helpers/tests/describeRating.spec.js
> +describe("describeRating gets a number and returns string with rate", () => {
In the upper "describe" you should write which function you're testing. In "it" you should write what the test case you're testing. E.g. 
describe("describeRating", () => {
  it('given a rating number - returns estimation string') ...

2022-02-04 08:24 UTC, alexanderchernetsky commented on src/utils/helpers/tests/expandList.spec.js
> +  test("get nothing and return string no data", () => {
Replace "get" with "given". It's incorrect from the English language perspective. Word "get" has a meaning - получить. In our tests "given" suits better.

2022-02-05 12:01 UTC, AlexeyGrishechkin commented on src/utils/helpers/tests/expandList.spec.js
> +  test("get nothing and return string no data", () => {
fixed

2022-02-05 12:02 UTC, AlexeyGrishechkin commented on src/utils/helpers/tests/describeRating.spec.js
> +describe("describeRating gets a number and returns string with rate", () => {
fixed

2022-02-05 12:02 UTC, AlexeyGrishechkin commented on src/utils/helpers/tests/createGenreList.spec.js
> +describe("createGenreList get genreList array of objects with id and name and filmGenre array of number (genres id) and returns names of genre as string", () => {
fixed

2022-02-05 12:02 UTC, AlexeyGrishechkin commented on src/utils/helpers/tests/createGenreList.spec.js
> +const genreList = [
fixed

2022-02-05 12:02 UTC, AlexeyGrishechkin commented on src/utils/helpers/tests/checkData.spec.js
> +  test("get only one parameter and return string", () => {
fixed

2022-02-05 12:02 UTC, AlexeyGrishechkin commented on src/utils/helpers/tests/checkData.spec.js
> +describe("checkData gets two parameters and returns these joined parameters as string", () => {
fixed

2022-02-05 12:02 UTC, AlexeyGrishechkin commented on src/utils/helpers/expandList.js
> +  if (list.length === 0 || filterList.length === 0) {
fixed

2022-02-05 12:02 UTC, AlexeyGrishechkin commented on src/utils/helpers/expandList.js
> +export const expandList = (list = []) => {
fixed

2022-02-05 12:02 UTC, AlexeyGrishechkin commented on src/utils/helpers/describeRating.js
> +    convertRatingToNumber === 0 ||
fixed

2022-02-05 12:02 UTC, AlexeyGrishechkin commented on src/utils/helpers/describeRating.js
> +  const convertRatingToNumber = Number(rating);
fixed

2022-02-05 12:02 UTC, AlexeyGrishechkin commented on src/utils/helpers/createGenreList.js
> +  const findGenresInGenresList = genreList.filter(
fixed

2022-02-06 18:51 UTC, merged